### ISSUE TITLE
Documentation of the user roles via OIDC provider & User role with read-only rights

### ISSUE THREAD

**Issue by Malte96** [N5GEH/n5geh.tutorials.entirety_step_by_step#17]
Please include documentation of the possible user roles and the associated rights. The readme only contains an overview of the possible roles.

In addition, a user role with read-only rights would be great.

**Comment by Malte96** [comment]
I have just seen the definition in the user profile in the app, a documentation in the readme would make it easier to use

- super-admin: Designates that this user has all permissions without explicitly assigning them.
- server-admin: User can create and update projects for any project admin.
- project-admin: User can create projects and update self created.
- user: User can edit existing projects that have been shared for them

**Comment by SBlechmann** [comment]
This is dealt with in https://github.com/N5GEH/n5geh.tools.entirety/issues/184
