### ISSUE TITLE
Update docker-compose file 

### ISSUE THREAD

**Issue by JRadebold** [N5GEH/n5geh.tutorials.entirety_step_by_step#9]
The ports in the postgres image need to be exposed, otherwise django want start
` ports: - "5432:5432" `
 And  then [here](https://github.com/N5GEH/n5geh.tutorials.entirety_step_by_step/blob/main/docker/docker-compose.yml#L10C9-L10C9) perhaps change ` POSTGRES_PASSWORD=${POSTGRES_PASSWORD}` to 
`- POSTGRES_PASSWORD=${DATABASE_PASSWORD}`, because [here](https://github.com/N5GEH/n5geh.tools.entirety/blob/development/app/Entirety/entirety/settings.py#L26C1-L26C1) in the database settings and [here](https://github.com/N5GEH/n5geh.tools.entirety/blob/development/app/Entirety/.env.EXAMPLE#L9C1-L9C29) in the example .env  it's called DATABASE_PASSWORD

**Comment by djs0109** [comment]
Thank you for reporting! We will update the files asap.

**Comment by djs0109** [comment]
related with https://github.com/N5GEH/n5geh.tools.entirety/issues/112

**Comment by JRadebold** [comment]
Hey @djs0109, I just tried the new Docker file with the newly merged development branch and it is not working unfortunately. I think the authentication for Postgres isn’t going through, but i am not entirely sure. I tried to fix it but couldn’t, so maybe you have a second look at it or perhaps together? Thank you :)
